# Generated by Django 3.1.6 on 2021-05-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Public',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=20, null=True)),
                ('phone', models.IntegerField()),
                ('datee', models.IntegerField()),
                ('content', models.CharField(max_length=20, null=True)),
                ('weight', models.IntegerField()),
                ('pickup', models.CharField(max_length=20, null=True)),
                ('delivery', models.CharField(max_length=20, null=True)),
                ('message', models.CharField(max_length=20, null=True)),
                ('status', models.BooleanField(verbose_name=0)),
            ],
        ),
    ]
